# Generated by Django 5.0.2 on 2024-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('raza', models.CharField(blank=True, max_length=45, null=True)),
                ('nom_mas', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_naci', models.DateField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MascotaServicio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField()),
            ],
            options={
                'db_table': 'mascota_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=45)),
                ('desc_pro', models.CharField(max_length=45)),
                ('precio_pro', models.FloatField()),
                ('foto', models.CharField(blank=True, max_length=45, null=True)),
                ('stock', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoUsuario',
            fields=[
                ('codpu', models.IntegerField(db_column='codPU', primary_key=True, serialize=False)),
                ('cant', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'producto_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servi', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('imagen', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=45, null=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('ape', models.CharField(blank=True, max_length=45, null=True)),
                ('dir', models.CharField(blank=True, max_length=45, null=True)),
                ('tel', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
